#===============================================================================
# Meta Data
#===============================================================================

metadata:
    id: special-swe
    language: swe
    description:
        eng: |
            This test corpus includes:
            - XML headers
            - re-naming of elements and attributes on import
            - special source_annotations syntax
            - sub-token source annotations

#===============================================================================
# Import Settings
#===============================================================================

import:
    # The annotation representing one text document. Any text-level annotations will be attached to this annotation.
    document_annotation: text

xml_import:
    # Elements that should be treated as headers, i.e. their contents will not be part of the corpus text
    header_elements:
        - header
        - another-header
    # Header elements and attributes from which we want to extract metadata
    header_data:
        - header/författare as text:author
        - header/författare:birth as text:author-birth
        - header/författare:death as text:author-death
        - header/title/main-title as text:title
        - header/title/sub-title as text:subtitle
        - header/date as text:date
    elements:
        - paragraph:n as id
        - paragraph as p
    skip:
        - i
        - u:@contents

#===============================================================================
# Export Settings
#===============================================================================

export:
    # Exports to create by default when running 'sparv run'
    default:
        - csv_export:csv
        - cwb:info
        - cwb:vrt
        - cwb:vrt_scrambled
        - xml_export:pretty
        - xml_export:preserved_format
        - xml_export:scrambled
    # Annotations from original documents to include in the output. If nothing is specified, everything is kept.
    source_annotations:
        - dokument as document
        - not text:subtitle
        - ...
    # Headers from the original documents that we want to include in the output
    header_annotations:
        - header
    # Automatic annotations to be included in the export
    annotations:
        - <sentence>:misc.id
        - <token>
