classes:
  token:msd: <token>:stanza.msd
export:
  annotations:
  - <token>:saldo.baseform
  - segment.token
  - segment.sentence
  - segment.paragraph
  - <token>:stanza.msd
  - <token>:stanza.pos
  - <token>:stanza.baseform
import:
  document_annotation: speech
  importer: xml_import:parse
  source_dir: source
metadata:
  id: riksdagens-protokoll
  language: swe
  name:
    eng: Riksdagens protokoll

xml_import:
  skip:
  - teiCorpus:xmlns
  - teiHeader:@contents
  - note:@contents
