[tool.poetry]
name = "penelope-parla-clarin-pipeline"
version = "2021.3.1"
description = "Pipeline that transforms Parla-Clarin XML files"
authors = ["Roger Mähler <roger.mahler@hotmail.com>"]
packages = [
    { include = "pipelines" }
]
classifiers = [
    'License :: OSI Approved :: Apache Software License',
    'Operating System :: OS Independent',
    'Topic :: Software Development',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.8',
]
license = "Apache-2.0"
readme = "README.md"
homepage = "https://westac.se"
repository = "https://github.com/welfare-state-analytics/parla_clarin_pipeline"

[tool.poetry.dependencies]
python = "^3.8"
snakemake = "^5.32.2"
xmltodict = "^0.12.0"
untangle = "^1.1.1"
Jinja2 = "^2.11.3"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
coverage = "^5.4"
dephell = "^0.8.3"
flake8 = "^3.8.4"
flake8-black = "^0.2.1"
isort = "^5.7.0"
mypy = "^0.812"
pre-commit = "^2.10.1"
pycodestyle = "^2.6.0"
pyflakes = "^2.2.0"
pylint = "^2.7.1"
pytest = "^6.2.2"
pytest-cov = "^2.11.1"
rope = "^0.18.0"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = [
    "-ra",
    "-q",
    # "-s",
]
log_cli = "False"
testpaths = [
    "tests",
]
python_files = "*_test.py"
python_functions = "test_*"
filterwarnings = [
#   "ignore",
  "ignore::_pytest.warning_types.PytestCollectionWarning"
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
