metadata:
    id: proto
    name:
        eng: proto
        swe: proto
    language: swe
    description:
        eng: proto
        swe: ''
import:
    source_dir: source
    importer: text_import:parse
    document_annotation: text
export:
    default:
        - csv_export:csv
        - xml_export:pretty
    annotations:
        - <token>:stanza.pos
        - <token>:stanza.baseform
