metadata:
    id: protocols
    name:
        eng: protocols
        swe: protocols
    language: swe
    description:
        eng: Riksdagens protokoll
        swe: Riksdagens protokoll
import:
    source_dir: source
    importer: xml_import:parse
    document_annotation: seg
export:
    default:
        - xml_export:pretty
    annotations:
        - <token>:stanza.pos
        - <token>:stanza.baseform

