#===============================================================================
# Meta Data
#===============================================================================

metadata:
    # Corpus ID (Machine name, only lower case ASCII letters (a-z) and "-" allowed. No white spaces.)
    id: freeling-eng-slevel
    # Corpus name (human readable)
    name:
        eng: FreeLing test corpus
    # Language of the input documents, specified as ISO 639-3 code
    language: eng

    description:
        eng: |
            This test corpus includes:
            - the FreeLing_FULL annotations from the FREELING preset
            - annotations with slevel (meaning that FreeLing won't do sentence segmentation)
            - some exports

#===============================================================================
# Import Settings
#===============================================================================

import:
    # The annotation representing one text document. Any text-level annotations will be attached to this annotation.
    document_annotation: text

xml_import:
    elements:
        - s
        - text:date

#===============================================================================
# Annotation Class Settings
#===============================================================================

classes:
    sentence: s

#===============================================================================
# Module Settings
#===============================================================================

freeling:
    sentence_annotation: s

# Description of the date/time input format
dateformat:
    datetime_from: <text>:date
    datetime_to: <text>:date
    datetime_informat: "%Y-%m-%d"

#===============================================================================
# Export Settings
#===============================================================================

export:
    # Exports to create by default when running 'sparv run'
    default:
        - csv_export:csv
        - cwb:info
        - cwb:vrt
        - cwb:vrt_scrambled
        - korp:timespan_sql
        - stats_export:freq_list_simple
        - xml_export:pretty
        - xml_export:preserved_format
    # Automatic annotations to be included in the export
    annotations:
        - <text>:readability.lix
        - DATETIME.all
        - s:misc.id
        - FREELING_FULL.token
