#===============================================================================
# Meta Data
#===============================================================================

metadata:
    # Corpus ID (Machine name, only lower case ASCII letters (a-z) and "-" allowed. No white spaces.)
    id: standard-swe
    # Corpus name (human readable)
    name:
        eng: Swedish standard test corpus

    description:
        eng: |
            This test corpus includes:
            - all Swedish standard token and text-level annotations except wsd
            - custom annotations
            - all kinds of exports except the combined and compressed variants


#===============================================================================
# Import Settings
#===============================================================================

import:
    # The annotation representing one text document. Any text-level annotations will be attached to this annotation.
    document_annotation: text

xml_import:
    # Elements and attributes from the source XML that we want to be available as input for other annotations
    elements:
        - text:date

#===============================================================================
# Annotation Class Settings
#===============================================================================

# Class definitions
classes:
    "token:sense": <token>:saldo.sense

#===============================================================================
# Module Settings
#===============================================================================

segment:
    # Chunk to use for automatic sentence segmentation (typically text or paragraph)
    sentence_chunk: <paragraph>

# Description of the date/time input format
dateformat:
    datetime_from: <text>:date
    datetime_to: <text>:date
    datetime_informat: "%Y-%m-%d"

#===============================================================================
# Export Settings
#===============================================================================

export:
    # Exports to create by default when running 'sparv run'
    default:
        - conll_export:conllu
        - csv_export:csv
        - cwb:info
        - cwb:vrt
        - cwb:vrt_scrambled
        - korp:relations_sql
        - korp:timespan_sql
        - stats_export:freq_list
        - xml_export:pretty
        - xml_export:preserved_format
        - xml_export:scrambled
    # Automatic annotations to be included in the export
    annotations:
        - DATETIME.all
        - PARAGRAPH_SWE.all
        - SWE_DEFAULT.all
        - not <token>:wsd.sense
        - <token>:misc.word.affixed
        - <token>:custom.convert.upper

#===============================================================================
# Custom Annotations
#===============================================================================
custom_annotations:
    - annotator: misc:affix
      params:
          out: <token>:misc.word.affixed
          chunk: <token:word>
          prefix: "|"
          suffix: "|"

    - annotator: custom.convert:uppercase
