#===============================================================================
# Meta Data
#===============================================================================

metadata:
    # Corpus ID (Machine name, only lower case ASCII letters (a-z) and "-" allowed. No white spaces.)
    id: mini-swe
    # Corpus name (human readable)
    name:
        eng: Swedish test corpus with quick annotations

    description:
        eng: |
            This test corpus includes:
            - some Swedish standard token and text-level annotations that can be done quickly
            - re-naming of attributes ("as" notation)
            - combined XML export

#===============================================================================
# Import Settings
#===============================================================================

import:
    # The annotation representing one text document. Any text-level annotations will be attached to this annotation.
    document_annotation: text

#===============================================================================
# Annotation Class Settings
#===============================================================================

classes:
    "token:pos": <token>:stanza.pos
    "token:msd": <token>:stanza.msd
    "token:baseform": <token>:saldo.baseform

#===============================================================================
# Export Settings
#===============================================================================

export:
    # Exports to create by default when running 'sparv run'
    default:
        - csv_export:csv
        - cwb:info
        - cwb:vrt
        - cwb:vrt_scrambled
        - korp:timespan_sql
        - stats_export:freq_list_simple
        - xml_export:pretty
        - xml_export:preserved_format
        - xml_export:scrambled
        - xml_export:combined
    # Automatic annotations to be included in the export
    annotations:
        - <sentence>:misc.id
        - <token:baseform>
        - <token:pos>
        - <token>:sensaldo.sentiment_label
    # Annotations from original documents to include in the output. If nothing is specified, everything is kept.
    source_annotations:
        - dokument as document
        - text:forfattare as author
        - ...

csv_export:
    # Overriding export.source_annotations
    source_annotations:
        - text:id
        - text:date
        - text:forfattare as author
