root_folder: /data/riksdagen_corpus_data
target_folder: /data/riksdagen_corpus_data/tagged_frames_v0.4.5
repository_folder: /data/riksdagen_corpus_data/riksdagen-corpus
repository_branch: v0.4.5
source_folder: /data/riksdagen_corpus_data/riksdagen-corpus/corpus/protocols
