root_folder: tests/output/work_folder
target_folder: tests/output
repository_folder: tests/output/work_folder/riksdagen-corpus
repository_branch: v0.4.3
source_folder: tests/output/work_folder/riksdagen-corpus/corpus/protocols/1936
