#===============================================================================
# Meta Data
#===============================================================================

metadata:
    # Corpus ID (Machine name, only lower case ASCII letters (a-z) and "-" allowed. No white spaces.)
    id: stanford-eng
    # Corpus name (human readable)
    name:
        eng: Stanford Parser test corpus
    # Language of the input documents, specified as ISO 639-3 code
    language: eng

    description:
        eng: |
            This test corpus includes:
            - the Stanford Parser annotations from the STANFORD preset
            - some exports

#===============================================================================
# Import Settings
#===============================================================================

import:
    # The annotation representing one text document. Any text-level annotations will be attached to this annotation.
    document_annotation: text


#===============================================================================
# Export Settings
#===============================================================================

export:
    # Exports to create by default when running 'sparv run'
    default:
        - korp:timespan_sql
        - cwb:info
        - csv_export:csv
        - cwb:vrt
        - cwb:vrt_scrambled
        - stats_export:freq_list_simple
        - xml_export:pretty
        - xml_export:preserved_format
    # Automatic annotations to be included in the export
    annotations:
        - STANFORD.all
