metadata:
    id: parla-clarin-test
    name:
        eng: Riksdagens Corpus
        swe: Riksdagens Korpus
    language: swe
    description:
        eng: |+
            Riksdagens Protokoll

        swe: Riksdagens Protokoll
import:
    source_dir: source
    importer: xml_import:parse
    document_annotation: u
export:
    source_annotations:
        - 'docDate:when'
        - 'head'
        - 'seg'
        - 'seg:n'
        - 'u'
        - 'u:n'
        - 'u:next'
        - 'u:prev'
        - 'u:who'
        - 'u:id'
    default:
        - csv_export:csv
        - xml_export:pretty
    annotations:
        - <token>:hunpos.pos
        - <token>:saldo.lemgram
        - <token>:saldo.baseform
classes:
    token:msd: <token>:hunpos.msd

xml_import:
  skip:
  - teiCorpus:xmlns
  - teiHeader:@contents
  - note:@contents